language: php
php:
  - '7.1'
services:
  - mongodb

before_install:
  - pecl install mongodb
  #- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sleep 15

install:
  - 'composer install'

script:
  - 'vendor/bin/phpunit tests/'


